"""empty message

Revision ID: 0ddd4a39d855
Revises: d35d6166405c
Create Date: 2018-01-04 19:37:40.522594

"""

# revision identifiers, used by Alembic.
revision = '0ddd4a39d855'
down_revision = 'd35d6166405c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('day', sa.Text(), nullable=True))
    op.add_column('medication', sa.Column('day', sa.Text(), nullable=True))
    op.add_column('nutrition', sa.Column('day', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutrition', 'day')
    op.drop_column('medication', 'day')
    op.drop_column('exercise', 'day')
    # ### end Alembic commands ###
