"""empty message

Revision ID: 1e5715d7b74d
Revises: 30a3f2071b5a
Create Date: 2018-01-04 23:47:49.587340

"""

# revision identifiers, used by Alembic.
revision = '1e5715d7b74d'
down_revision = '30a3f2071b5a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'day')
    op.add_column('medication', sa.Column('days', sa.Text(), nullable=True))
    op.drop_column('medication', 'day')
    op.add_column('nutrition', sa.Column('days', sa.Text(), nullable=True))
    op.drop_column('nutrition', 'day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition', sa.Column('day', sa.TEXT(), nullable=True))
    op.drop_column('nutrition', 'days')
    op.add_column('medication', sa.Column('day', sa.TEXT(), nullable=True))
    op.drop_column('medication', 'days')
    op.add_column('exercise', sa.Column('day', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
