"""empty message

Revision ID: 1ea5fa9c2c4f
Revises: None
Create Date: 2017-09-17 19:16:52.313107

"""

# revision identifiers, used by Alembic.
revision = '1ea5fa9c2c4f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
