"""empty message

Revision ID: 42adddd8b477
Revises: e12653c39709
Create Date: 2018-02-05 22:03:48.484111

"""

# revision identifiers, used by Alembic.
revision = '42adddd8b477'
down_revision = 'e12653c39709'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_todo', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_todo', 'status')
    # ### end Alembic commands ###
