"""empty message

Revision ID: d35d6166405c
Revises: 2ea6bf8de8ee
Create Date: 2017-10-27 04:09:20.521701

"""

# revision identifiers, used by Alembic.
revision = 'd35d6166405c'
down_revision = '2ea6bf8de8ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_descriptions')
    op.drop_table('resources')
    op.drop_table('exercises')
    op.drop_table('plan_components')
    op.add_column('users', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'plan', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'plan_id')
    op.create_table('plan_components',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fk_table', sa.VARCHAR(length=64), nullable=True),
    sa.Column('fk_id', sa.INTEGER(), nullable=True),
    sa.Column('plan_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], [u'plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('resources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('aws_url', sa.VARCHAR(length=10000), nullable=True),
    sa.Column('exercise_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], [u'exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_descriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('form_link', sa.TEXT(), nullable=True),
    sa.Column('plan_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], [u'plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
