"""empty message

Revision ID: e12653c39709
Revises: 1e5715d7b74d
Create Date: 2018-02-05 21:09:52.586024

"""

# revision identifiers, used by Alembic.
revision = 'e12653c39709'
down_revision = '1e5715d7b74d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_component_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_component_id'], ['plan_component.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_todo')
    # ### end Alembic commands ###
