"""empty message

Revision ID: f295a06e7d90
Revises: e9f31a041383
Create Date: 2018-02-06 00:53:35.389039

"""

# revision identifiers, used by Alembic.
revision = 'f295a06e7d90'
down_revision = 'e9f31a041383'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
